import Head from "next/head";
import ArticleList from "../components/ArticleList";
import styles from "../styles/Home.module.css";

export default function Home({article}) {
  console.log(article)
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <ArticleList article={article}/>
    </div>
  );
}

export const getStaticProps = async () => {
  const res =  await fetch('https://jsonplaceholder.typicode.com/posts?_limit=8')
  const article = await res.json()

  return {
    props: {
      article
    }
  }
}
